sudo: required
services:
  - docker
language: android
jdk: oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
before_install:
  - docker pull influxdb
  - docker run --name=influxdb -d -p 127.0.0.1:8086:8086 influxdb
  - docker ps -a
env:
 global:
 - ANDROID_API_LEVEL=26
 - ANDROID_BUILD_TOOLS=26.0.2
android:
  components:
  - tools
  - platform-tools
  - tools # Running this twice get's the latest build tools
  - android-$ANDROID_API_LEVEL
  - build-tools-$ANDROID_BUILD_TOOLS
script:
 - android list target
 - curl -i -XPOST http://127.0.0.1:8086/query --data-urlencode "q=CREATE DATABASE test"
 - ./gradlew clean test build
