# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
     crashlytics(
        api_token: ENV["FABRIC_API_TOKEN"],
        build_secret: ENV["FABRIC_BUILD_SECRET"],
        apk_path: ENV["APK_PATH"]
      )

  end
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    begin
    supply(track: "production",
           package_name: "science.apolline",
           apk: ENV["APK_PATH"])
    rescue => exception
        on_error(exception)
    end
  end
end
