# Tag last commit as 'latest'.
if [ "$TRAVIS_BRANCH" = "travisci" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
  git config --global user.email "apolline@travis-ci.org"
  git config --global user.name "Sr. Travis"

  git remote add release "https://${GH_TOKEN}@github.com/Apolline-Lille/apolline-android.git"

  git push -d release latest
  git tag -d latest
  git tag -a "alpha.1" -m "[Autogenerated] This is the latest version pushed to the travisci branch."
  git push release --tags
fi
